apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    prometheus.io/scrape: "true"
  labels:
    app: kratos-template-bff
    version: v1
  name: kratos-template-bff
  namespace: kratos-template-bff-namespace
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kratos-template-bff
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kratos-template-bff
    spec:
      containers:
        - env:
            - name: GOLANG_PROTOBUF_REGISTRATION_CONFLICT
              value: ignore
          image: mirror.camera360.com
          imagePullPolicy: IfNotPresent
          name: kratos-template-bff
          command: ["/app/bin/app", "-env", "prod"]
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
            - name: kratos-template-bff-configmap
              mountPath: /app-config
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aliregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: volume-localtime
        - name: kratos-template-bff-configmap
          configMap:
            name: kratos-template-bff-configmap
